# This file specifies the tools and scripts to run as pre-commit checks,
# as well as their configurations (? an abstraction of pre-commit hook).
# https://github.com/pre-commit/pre-commit
#
# Required:
#
#   $ pip install pre-commit
#
# To run:
#
#   $ pre-commit run
#

# Run numpydoc-style docstring validation
# - repo: https://github.com/numpy/numpydoc
#   rev: <version>
#   hooks:
#     - id: numpydoc-validation
